name: TEST

on:
  workflow_dispatch:
  schedule:
    - cron: "25 9,21 * * *"
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          pacman -Syu --noconfirm base-devel sudo lib32-jack2 git vulkan-headers

      - name: Create User
        run: |
          useradd -m -G wheel -s /bin/bash user
          echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Compile Proton
        run: |
          chown -R user:user $PWD
          export CARGO_HOME="$PWD"
          mkdir -p proton-tkg/built
          tar -cvf proton-tkg/built/tested.tar proton-tkg/

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: proton-tkg-build
          path: proton-tkg/built/*.tar

      - name: Upload to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: proton-tkg/built/*.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
